### PR TITLE
show curl output for bulk deletions

### PR DESCRIPTION
**Pull request by max-mapper**
now the app generates strings like this that can be copy pasted into terminal:

```
curl -X POST http://max.ic.ht/critters/_bulk_docs -d '{"docs":[{"_id":"cd4887acbc965958e37a609baa0561a0","_rev":"1-2ad2e23a1c547dd3f76e46a013ecb951","_deleted":true}]}' -H 'content-type: application/json'
```

all you have to do is instead of http://max.ic.ht put http://user:pass@max.ic.ht for the deletions to go through

### CODE REVIEW

**Comment by max-mapper** [comment]
also it would be sweet to deploy this to gh-pages when you get a chance. I can also give you guys a username:password to use in case you need one, otherwise i'm happy to keep an eye on it now that it's easy to delete stuff

**Comment by derekr** [comment]
Yeah set me up with some credentials and I'll help manage whenever I have some spare time.

Deployed to github pages http://derekr.github.io/voxel-painter-admin/, but I am seeing an old build right now. The fix should be live soon.

**Comment by max-mapper** [comment]
@derekr you gotta check in `bundle.js` to `gh-pages`

**Comment by derekr** [comment]
That's embarrassing :x. Should be all set!

**Pull request merged**
